### ISSUE TITLE
DDA issue

### ISSUE THREAD

**Issue by arikhativa** [arikhativa/cub3d#61]
on a map like this:
```
1111111
1110101
100011
100N101
1111111
```

if i cast a ray from N {3.5, 1.5} to {3, 3.5} i dont hit anything

**Comment by arikhativa** [comment]
ok i found the isessue 

when we have a coll
we need more info

we need to know the fpoint 
but we also **must**  have the dir of coll

e.g.
```
10
00
0N
```
coll point is 2.0, 2.5
but the map index should be 1, 2 !!! (not 2, 2)

**Comment by m00nbyt3** [comment]
Ill do a PR in which I save a value depending on if it collides on X or Y, so it will be also useful when calculating the type of wall we nned to draw
