### ISSUE TITLE
All dda tests shoule change a bit

### ISSUE THREAD

**Issue by arikhativa** [arikhativa/cub3d#93]
there are issues conserning corners that we neeed to think about

test like this 
```
void	test_dda_perfect_nw(void)
```

should probably act diffrently

**Comment by m00nbyt3** [comment]
In this tests, there is a collision of corners, between (1,3) and (2,5)
So I think the collision is right but the test is wrong

**Comment by m00nbyt3** [comment]
If we change the map to this:
`char **map = util_create_rev_map(
		6,
		"111111",
		"111111",
		"110011",
		"111001",
		"1111N1",
		"111111"
	);`
	Then the collision is detected here:
	`CU_ASSERT_EQUAL(test.x, 2);
	CU_ASSERT_EQUAL(test.y, 4);`

**Comment by m00nbyt3** [comment]
char **map = util_create_rev_map(
		6,
		"111111",
		"111111",
		"110011",
		"111001",
		"1111N1",
		"111111"
	);
